### PR TITLE
All the fixes

### LINKED ISSUE #361: Deploying Plumber on DigitalOcean
Hello,
I tried to deploy my API on DigitalOcean and get Error in file(con, "wb") : cannot open the connection

```r
do_provision(unstable = TRUE, region = 'sgp1')
#> THIS ACTION COSTS YOU MONEY!
#> Provisioning a new server for which you will get a bill from DigitalOcean.
#> Adding .httr-oauth to .gitignore
#> Waiting for authentication in browser...
#> Press Esc/Ctrl + C to abort
#> Authentication complete.
#> Using default ssh keys: Caelestis
#> NB: This costs $0.00744 / hour until you droplet_delete() it
#> Waiting for create ..................
#> New server fingerprint: ba:91:9f:ba:88:93:f7:54:f9:2c:5d:9a:c3:ac:4d:eb:db:6d:41:06
#> 2 C:\Users\CAELES1\AppData\Local\Temp\RtmpuYaaRl\file74c014d55ca2/JmoftZKayv
#> Error in file(con, "wb") : cannot open the connection
#> In addition: Warning message:
#> In file(con, "wb") :
#> cannot open file 'C:\Users\CAELES1\AppData\Local\Temp\RtmpuYaaRl\file74c014d55ca2/JmoftZKayv': #> No such file or directory
#> 
traceback()
#> 9: file(con, "wb")
#> 8: writeBin(data, target)
#> 7: (function (data, filepath) 
#>    {
#>        target <- do.call(file.path, as.list(c(to, filepath)))
#>        if (verbose) 
#>            cat(sprintf("%10d %s\n", length(data), target))
#>        if (is.null(data)) 
#>            return(dir.create(target, recursive = TRUE, showWarnings = FALSE))
#>        writeBin(data, target)
#>    })(as.raw(c(0x30, 0x0a)), "cWMJuYpixl")
#> 6: ssh::scp_download(session = session, files = remote, to = local, 
#>        verbose = TRUE)
#> 5: cat(ssh::scp_download(session = session, files = remote, to = local, 
#>        verbose = TRUE), sep = "\n")
#> 4: do_scp(droplet, local, remote, user, scp = "download", keyfile, 
#>        ssh_passwd, verbose = verbose)
#> 3: analogsea::droplet_download(droplet, paste0("/tmp/", randName), 
#>        tf)
#> 2: droplet_capture(droplet, "swapon | grep \"/swapfile\" | wc -l")
#> 1: plumber::do_provision(region = "sgp1")
```

### PR DESCRIPTION
**Pull request by trestletech**
Fixes #444 
Fixes #445
Fixes #446 

Fixes #361 

Additionally cleans up some upload behavior to accommodate the new ssh behavior in analogsea. I have NOT tested against old analogseas (on CRAN now).

### CODE REVIEW

**Comment by schloerke** [comment]
@sckott Do you mind signing the CLA so that we may merge this PR when our manual checks finish/pass?  Thank you for your help!!

File: R/digital-ocean.R [hunk 1]
```diff
@@ -91,20 +94,23 @@ install_plumber <- function(droplet, unstable){
 #' Captures the output from running some command via SSH
 #' @noRd
 droplet_capture <- function(droplet, command){
-    tf <- tempfile()
+    tf <- tempdir()
+    on.exit({
+      unlink(tf, recursive = TRUE)
```
Comment (jcheng5) [inline R/digital-ocean.R]: `unlink(tff)`

File: R/digital-ocean.R [hunk 2]
```diff
@@ -91,20 +94,23 @@ install_plumber <- function(droplet, unstable){
...
-    file.remove(tf)
+    lin <- readLines(tff)
     lin
 }
 
 install_api <- function(droplet){
   analogsea::droplet_ssh(droplet, "mkdir -p /var/plumber")
   analogsea::droplet_upload(droplet, local=normalizePath(
-      paste0(system.file("examples", "10-welcome", package="plumber"), "/**"), mustWork=FALSE), #TODO: Windows support for **?
+      paste0(system.file("examples", "10-welcome", "plumber.R", package="plumber")), mustWork=FALSE),
```
Comment (jcheng5) [inline R/digital-ocean.R]: Can we get rid of `normalizedPath`?
